[package]
name = "VaultManager"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]

[addresses]
vault_manager = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "devnet" }
